/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.griduser.swig;

class lcmaps_interfaceJNI {

  static {
    try {
      System.loadLibrary("lcmaps_interface");
    } catch (UnsatisfiedLinkError e) {
	  final String libfile 
			= "'" + System.mapLibraryName("lcmaps_interface") + "'";
	  final org.apache.log4j.Logger log 
			= org.apache.log4j.Logger.getLogger(lcmaps_interfaceJNI.class);
      log.fatal("Native code library " + libfile
				 + " failed to load: " + e.getMessage());
	  // give some informational details, may be useful when debugging
	  final String ldpath = System.getProperty("java.library.path");
	  if (null != ldpath) 
	    log.info("Java VM searched for " + libfile 
            + "in java.library.path: " + ldpath);
   	  else
		log.info("Java VM library search path is null!");
      log.info("Add the library location to the environment variable LD_LIBRARY_PATH or to the Java property java.library.path");
	  throw new UnsatisfiedLinkError("Native code library " + libfile
				 + " failed to load: " + e.getMessage());
    }
  }

  public final static native int get_localuser_info_uid(long jarg1);
  public final static native int[] get_localuser_info_gids(long jarg1);
  public final static native long get_localuser_info_ngids(long jarg1);
  public final static native long new_localuser_info(String jarg1, String[] jarg2);
  public final static native void delete_localuser_info(long jarg1);
}
