#!/bin/sh
# Build a zzz rpm set. 
# Uses temp space here, does not touch the source.
# Runnable as myself, does not use root permission at all.

PROG="`basename $0`"

usage () {
	cat <<EOF
Usage: $PROG SOURCE DEST VERSION 

Builds the tar package and put it in DEST location.
EOF
}

die () {
	rc="$1"
	shift

	echo -n "$PROG: "
	if [ -z "$1" ]; then cat 1>&2; else echo 1>&2 "$@"; fi
	
	exit $rc
}


## process cmd line args

source="$1";
dest="$2";
version="$3";
arch="$4";

echo "create directories"
mkdir -p -v $source/tgz
mkdir -p -v $source/tgz/{etc,etc/cron.d,etc/init.d,etc/sysconfig,doc,etc/db,etc/logrotate.d,sbin,var,var/log,var/tmp}
mkdir -p -v $source/tgz/lib$arch
mkdir -p -v $source/tgz/lib$arch/storm-backend

tgz=$source/tgz

files='/doc/AUTHORS
/doc/CREDITS
/doc/INSTALL.txt
/doc/LICENSE.txt
/etc/cron.d/storm-backend.cron
/etc/db/storm_database_config.sh 
/etc/db/storm_mysql_grant.sql 
/etc/db/storm_mysql_tbl.sql
/etc/db/storm_mysql_update_from_1.4.0_to_1.5.0.sql
/etc/db/storm_mysql_update_from_1.5.0_to_1.5.3.sql
/etc/db/storm_mysql_update_from_1.5.0_to_1.5.4.sql
/etc/db/storm_mysql_update_from_1.5.3_to_1.5.4.sql
/etc/init.d/storm-backend
/etc/lcmaps.db 
/etc/logging.xml
/etc/logrotate.d/storm-backend.logrotate
/etc/namespace-1.5.0.xsd
/etc/namespace.xml
/etc/path-authz.db
/etc/storm.properties.template 
/etc/sysconfig/storm-backend
/var/log
/var/tmp'

echo "copy files in tar directories"
cp $source/doc/INSTALL.txt $tgz/doc/INSTALL.txt
cp $source/AUTHORS $tgz/doc/AUTHORS
cp $source/CREDITS $tgz/doc/CREDITS
cp $source/LICENSE.txt $tgz/doc/LICENSE.txt
cp $source/etc/cron.d/storm-backend.cron $tgz/etc/cron.d/storm-backend.cron
cp $source/etc/db/storm_database_config.sh $tgz/etc/db/storm_database_config.sh
cp $source/etc/db/storm_mysql_grant.sql $tgz/etc/db/storm_mysql_grant.sql
cp $source/etc/db/storm_mysql_tbl.sql $tgz/etc/db/storm_mysql_tbl.sql
cp $source/etc/db/storm_mysql_update_from_1.4.0_to_1.5.0.sql $tgz/etc/db/storm_mysql_update_from_1.4.0_to_1.5.0.sql
cp $source/etc/db/storm_mysql_update_from_1.5.0_to_1.5.3.sql $tgz/etc/db/storm_mysql_update_from_1.5.0_to_1.5.3.sql
cp $source/etc/db/storm_mysql_update_from_1.5.0_to_1.5.4.sql $tgz/etc/db/storm_mysql_update_from_1.5.0_to_1.5.4.sql
cp $source/etc/db/storm_mysql_update_from_1.5.3_to_1.5.4.sql $tgz/etc/db/storm_mysql_update_from_1.5.3_to_1.5.4.sql
cp $source/etc/init.d/storm-backend $tgz/etc/init.d/storm-backend
cp $source/etc/lcmaps.db $tgz/etc/lcmaps.db
cp $source/etc/logging.xml $tgz/etc/logging.xml
cp $source/etc/logrotate.d/storm-backend.logrotate $tgz/etc/logrotate.d/storm-backend.logrotate
cp $source/etc/namespace.xml $tgz/etc/namespace.xml
cp $source/etc/namespace-1.5.0.xsd $tgz/etc/namespace-1.5.0.xsd
cp $source/etc/path-authz.db $tgz/etc/path-authz.db
cp $source/etc/storm.properties.template $tgz/etc/storm.properties.template
cp $source/etc/sysconfig/storm-backend $tgz/etc/sysconfig/storm-backend
cp $source/etc/welcome.txt $tgz/etc/welcome.txt
cp $source/build/lib$arch/libgpfsapi_interface.so $tgz/lib$arch/libgpfsapi_interface.so
cp $source/build/lib$arch/liblcmaps_interface.so $tgz/lib$arch/liblcmaps_interface.so
cp $source/build/lib$arch/libposixapi_interface.so $tgz/lib$arch/libposixapi_interface.so
cp $source/build/lib$arch/libstorm_cutil.so $tgz/lib$arch/libstorm_cutil.so
cp $source/build/lib$arch/libstorm_lcmaps.so $tgz/lib$arch/libstorm_lcmaps.so
cp $source/build/lib$arch/libxfsapi_interface.so $tgz/lib$arch/libxfsapi_interface.so
cp $source/build/storm-backend.jar $tgz/storm-backend.jar

# make rpm directory structure
echo "create tar structure "
echo $files

file1=""
for x in $files /lib$arch/libgpfsapi_interface.so /lib$arch/liblcmaps_interface.so /lib$arch/libposixapi_interface.so /lib$arch/libstorm_cutil.so /lib$arch/libstorm_lcmaps.so /lib$arch/libxfsapi_interface.so storm-backend.jar
do
#    echo $x
    file1="$tgz$x $file1"
    echo $file1 
done

cd $dest
echo "create tar file"
tar -zcvf storm-backend-server-$version.tar.gz $file1 


