/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AclWrapper */

#ifndef _Included_AclWrapper
#define _Included_AclWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AclWrapper
 * Method:    addAcl
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_AclWrapper_addAcl
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
