/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CompactSpaceWrapper */

#ifndef _Included_CompactSpaceWrapper
#define _Included_CompactSpaceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CompactSpaceWrapper
 * Method:    compactSpace
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_CompactSpaceWrapper_compactSpace
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
