/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_grid_storm_wrapper_TruncateWrapper */

#ifndef _Included_it_grid_storm_wrapper_TruncateWrapper
#define _Included_it_grid_storm_wrapper_TruncateWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_grid_storm_wrapper_TruncateWrapper
 * Method:    truncateFile
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_it_grid_storm_wrapper_TruncateWrapper_truncateFile
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
