/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_grid_storm_wrapper_RemoveAclWrapper */

#ifndef _Included_it_grid_storm_wrapper_RemoveAclWrapper
#define _Included_it_grid_storm_wrapper_RemoveAclWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_grid_storm_wrapper_RemoveAclWrapper
 * Method:    removeAcl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_grid_storm_wrapper_RemoveAclWrapper_removeAcl
  (JNIEnv *, jobject,jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
