/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_grid_storm_wrapper_GetAclWrapper */

#ifndef _Included_it_grid_storm_wrapper_GetAclWrapper
#define _Included_it_grid_storm_wrapper_GetAclWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_grid_storm_wrapper_GetAclWrapper
 * Method:    getAcl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_grid_storm_wrapper_GetAclWrapper_getAcl
  (JNIEnv *, jobject, jstring, jstring); 
#ifdef __cplusplus
}
#endif
#endif
