/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_grid_storm_wrapper_SpaceReservationWrapper */

#ifndef _Included_it_grid_storm_wrapper_SpaceReservationWrapper
#define _Included_it_grid_storm_wrapper_SpaceReservationWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_grid_storm_wrapper_SpaceReservationWrapper
 * Method:    reserveSpace
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_it_grid_storm_wrapper_SpaceReservationWrapper_reserveSpace
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
