/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_grid_storm_wrapper_CompactSpaceWrapper */

#ifndef _Included_it_grid_storm_wrapper_CompactSpaceWrapper
#define _Included_it_grid_storm_wrapper_CompactSpaceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_grid_storm_wrapper_CompactSpaceWrapper
 * Method:    compactSpace
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_grid_storm_wrapper_CompactSpaceWrapper_compactSpace
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
