/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_grid_storm_wrapper_StatWrapper */

#ifndef _Included_it_grid_storm_wrapper_StatWrapper
#define _Included_it_grid_storm_wrapper_StatWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_grid_storm_wrapper_StatWrapper
 * Method:    statfs
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_it_grid_storm_wrapper_StatWrapper_statfs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_grid_storm_wrapper_StatWrapper
 * Method:    stat
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_it_grid_storm_wrapper_StatWrapper_stat
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
