/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RemoveAclWrapper */

#ifndef _Included_RemoveAclWrapper
#define _Included_RemoveAclWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RemoveAclWrapper
 * Method:    removeAcl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_RemoveAclWrapper_removeAcl
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
