/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SpaceReservationWrapper */

#ifndef _Included_SpaceReservationWrapper
#define _Included_SpaceReservationWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SpaceReservationWrapper
 * Method:    reserveSpace
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_SpaceReservationWrapper_reserveSpace
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
