/*
 *
 *  Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2006-2010.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SpaceReservationWrapper */

#ifndef _Included_SpaceReservationWrapper
#define _Included_SpaceReservationWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SpaceReservationWrapper
 * Method:    reserveSpace
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_SpaceReservationWrapper_reserveSpace
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
