/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class error extends it.grid.storm.filesystem.FilesystemError {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected error(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected error() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      posixapi_interfaceJNI.delete_error(swigCPtr);
    }
    swigCPtr = 0;
  }

  public error(String reason) {
    this(posixapi_interfaceJNI.new_error(reason), true);
  }

  public String getMessage() {
    return posixapi_interfaceJNI.error_getMessage(swigCPtr);
  }

}
