/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class invalid_path extends error {
  private long swigCPtr;

  protected invalid_path(long cPtr, boolean cMemoryOwn) {
    super(posixapi_interfaceJNI.SWIGinvalid_pathUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(invalid_path obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected invalid_path() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      posixapi_interfaceJNI.delete_invalid_path(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public invalid_path(String reason) {
    this(posixapi_interfaceJNI.new_invalid_path(reason), true);
  }

}
