/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifdef __cplusplus
template<class T> class SwigValueWrapper {
    T *tt;
public:
    SwigValueWrapper() : tt(0) { }
    SwigValueWrapper(const SwigValueWrapper<T>& rhs) : tt(new T(*rhs.tt)) { }
    SwigValueWrapper(const T& t) : tt(new T(t)) { }
    ~SwigValueWrapper() { delete tt; } 
    SwigValueWrapper& operator=(const T& t) { delete tt; tt = new T(t); return *this; }
    operator T&() const { return *tt; }
    T *operator&() { return tt; }
private:
    SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
};
#endif


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99


static void SWIG_JavaException(JNIEnv *jenv, int code, const char *msg) {
  SWIG_JavaExceptionCodes exception_code = SWIG_JavaUnknownError;
  switch(code) {
  case SWIG_MemoryError:
    exception_code = SWIG_JavaOutOfMemoryError;
    break;
  case SWIG_IOError:
    exception_code = SWIG_JavaIOException;
    break;
  case SWIG_SystemError:
  case SWIG_RuntimeError:
    exception_code = SWIG_JavaRuntimeException;
    break;
  case SWIG_OverflowError:
  case SWIG_IndexError:
    exception_code = SWIG_JavaIndexOutOfBoundsException;
    break;
  case SWIG_DivisionByZero:
    exception_code = SWIG_JavaArithmeticException;
    break;
  case SWIG_SyntaxError:
  case SWIG_ValueError:
  case SWIG_TypeError:
    exception_code = SWIG_JavaIllegalArgumentException;
    break;
  case SWIG_UnknownError:
  default:
    exception_code = SWIG_JavaUnknownError;
    break;
  }
  SWIG_JavaThrowException(jenv, exception_code, msg);
}
#define SWIG_exception(code, msg) { SWIG_JavaException(jenv, code, msg); }


#include <stdexcept>


#include <string>


#include "fs_errors.hpp"


#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>


#include "genericfs.hpp"


#include "posixfs.hpp"


// these typemaps work only with C++
#ifndef __cplusplus
#error "pass_vector_by_value.i typemaps can only be used within C++ code!"
#endif


#include <vector>  // std::vector


#if 0 || 0


// prototype for Int[] --> std::vector<gid_t> conversion
int SWIG_JavaVectorInInt (JNIEnv *jenv, jint **jarr, 
                                  std::vector<gid_t> *output_container, 
                                  jintArray input);
// prototypes for std::vector<gid_t> --> Int[] conversion
void SWIG_JavaVectorArgoutInt (JNIEnv *jenv, jint *jarr, 
                                       std::vector<gid_t> &input_container,
                                       jintArray input);
jintArray SWIG_JavaVectorOutInt (JNIEnv *jenv, 
                                              std::vector<gid_t> &input_container,
                                              jsize sz);


#else
#ifndef JAVA_TYPEMAP_CONTAINER_APPEND
#define JAVA_TYPEMAP_CONTAINER_APPEND(gid_t) (*output_container).push_back((*jarr)[i])
#endif 


  // Int[] (jint##Array) --> std::vector<gid_t> 
int SWIG_JavaVectorInInt (JNIEnv *jenv, jint **jarr, 
                                  std::vector<gid_t> *output_container, 
                                  jintArray input) 
{
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  jsize sz;
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetIntArrayElements(input, 0);
  if (!*jarr)
    return 0; 
 try {
   //*output_container =  new std::vector<gid_t>;
   (*output_container).reserve(sz);
 }
 catch (std::bad_alloc err) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, 
                            "std::vector allocation failed");
    return 0;
 }
 for (int i=0; i<sz; i++)
    JAVA_TYPEMAP_CONTAINER_APPEND(gid_t);
  return 1;
}

  // std::vector<gid_t> --> jint[]
void SWIG_JavaVectorArgoutInt (JNIEnv *jenv, jint *jarr, 
                                       std::vector<gid_t> &input_container,
                                       jintArray input) 
{
  jsize sz = jenv->GetArrayLength(input);
  jint *jarrptr = jarr; 
  std::vector<gid_t>::const_iterator elt = input_container.begin();
  while (elt != input_container.end()) {
    if (0 == sz--)
      // bail out if no more space in Java array
      // XXX: should throw exception?
      break;
    *jarrptr++ = (jint) *elt;
    ++elt;
  }
  jenv->ReleaseIntArrayElements(input, jarr, 0);
}

// std::vector<gid_t> --> jint[]
jintArray SWIG_JavaVectorOutInt (JNIEnv *jenv, 
                                              std::vector<gid_t> &input_container, 
                                              jsize sz) 
{
  jintArray jresult = jenv->NewIntArray(sz);
  if (!jresult)
    return NULL;
  jint *arr = jenv->GetIntArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  jint *jarrptr = arr; 
  std::vector<gid_t>::const_iterator elt = input_container.begin();
  while (elt != input_container.end()) {
    if (0 == sz--)
      // bail out if no more space in Java array
      // XXX: should throw exception?
      break;
    *jarrptr++ = (jint) *elt;
    ++elt;
  }
  jenv->ReleaseIntArrayElements(jresult, arr, 0);
  return jresult;
}


#endif


#include "fs_acl.hpp"


#include "posixfs_acl.hpp"


#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1error(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::error *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    result = (fs::error *)new fs::error((std::string const &)*arg1);
    
    *(fs::error **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1error(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::error *arg1 = (fs::error *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::error **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jstring JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_error_1getMessage(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jstring jresult = 0 ;
    fs::error *arg1 = (fs::error *) 0 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::error **)&jarg1; 
    result = (char *)((fs::error const *)arg1)->what();
    
    {
        if(result) jresult = jenv->NewStringUTF(result); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1system_1error_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    int arg2 ;
    fs::system_error *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    arg2 = (int)jarg2; 
    result = (fs::system_error *)new fs::system_error((std::string const &)*arg1,arg2);
    
    *(fs::system_error **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1system_1error_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::system_error *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    result = (fs::system_error *)new fs::system_error((std::string const &)*arg1);
    
    *(fs::system_error **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1system_1error(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::system_error *arg1 = (fs::system_error *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::system_error **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jstring JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_system_1error_1getMessage(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jstring jresult = 0 ;
    fs::system_error *arg1 = (fs::system_error *) 0 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::system_error **)&jarg1; 
    result = (char *)((fs::system_error const *)arg1)->what();
    
    {
        if(result) jresult = jenv->NewStringUTF(result); 
    }
    return jresult;
}


JNIEXPORT jstring JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_system_1error_1error_1message(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jstring jresult = 0 ;
    fs::system_error *arg1 = (fs::system_error *) 0 ;
    int arg2 ;
    std::string result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::system_error **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (arg1)->error_message(arg2);
    
    jresult = jenv->NewStringUTF((&result)->c_str()); 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1acl_1not_1supported_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    fs::acl_not_supported *result;
    
    (void)jenv;
    (void)jcls;
    result = (fs::acl_not_supported *)new fs::acl_not_supported();
    
    *(fs::acl_not_supported **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1acl_1not_1supported_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::acl_not_supported *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    result = (fs::acl_not_supported *)new fs::acl_not_supported((std::string const &)*arg1);
    
    *(fs::acl_not_supported **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1acl_1not_1supported(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::acl_not_supported *arg1 = (fs::acl_not_supported *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::acl_not_supported **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1invalid_1path(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::invalid_path *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    result = (fs::invalid_path *)new fs::invalid_path((std::string const &)*arg1);
    
    *(fs::invalid_path **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1invalid_1path(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::invalid_path *arg1 = (fs::invalid_path *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::invalid_path **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1permission_1denied(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::permission_denied *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    result = (fs::permission_denied *)new fs::permission_denied((std::string const &)*arg1);
    
    *(fs::permission_denied **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1permission_1denied(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::permission_denied *arg1 = (fs::permission_denied *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::permission_denied **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1wrong_1filesystem_1type(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::wrong_filesystem_type *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    result = (fs::wrong_filesystem_type *)new fs::wrong_filesystem_type((std::string const &)*arg1);
    
    *(fs::wrong_filesystem_type **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1wrong_1filesystem_1type(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::wrong_filesystem_type *arg1 = (fs::wrong_filesystem_type *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::wrong_filesystem_type **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_chmod(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
    jint jresult = 0 ;
    char *arg1 = (char *) 0 ;
    mode_t arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
            if (!arg1) return 0;
        }
    }
    arg2 = (mode_t)jarg2; 
    result = (int)chmod((char const *)arg1,arg2);
    
    jresult = (jint)result; 
    {
        if (arg1) jenv->ReleaseStringUTFChars(jarg1, arg1); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_chown(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    char *arg1 = (char *) 0 ;
    uid_t arg2 ;
    gid_t arg3 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
            if (!arg1) return 0;
        }
    }
    arg2 = (uid_t)jarg2; 
    arg3 = (gid_t)jarg3; 
    result = (int)chown((char const *)arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg1) jenv->ReleaseStringUTFChars(jarg1, arg1); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_creat(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
    jint jresult = 0 ;
    char *arg1 = (char *) 0 ;
    mode_t arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
            if (!arg1) return 0;
        }
    }
    arg2 = (mode_t)jarg2; 
    result = (int)creat((char const *)arg1,arg2);
    
    jresult = (jint)result; 
    {
        if (arg1) jenv->ReleaseStringUTFChars(jarg1, arg1); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_mkdir(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
    jint jresult = 0 ;
    char *arg1 = (char *) 0 ;
    mode_t arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
            if (!arg1) return 0;
        }
    }
    arg2 = (mode_t)jarg2; 
    result = (int)mkdir((char const *)arg1,arg2);
    
    jresult = (jint)result; 
    {
        if (arg1) jenv->ReleaseStringUTFChars(jarg1, arg1); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_setuid(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    uid_t arg1 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (uid_t)jarg1; 
    result = (int)setuid(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_unlink(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jint jresult = 0 ;
    char *arg1 = (char *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
            if (!arg1) return 0;
        }
    }
    result = (int)unlink((char const *)arg1);
    
    jresult = (jint)result; 
    {
        if (arg1) jenv->ReleaseStringUTFChars(jarg1, arg1); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_umask(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    mode_t arg1 ;
    mode_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (mode_t)jarg1; 
    result = (mode_t)umask(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_geteuid(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    uid_t result;
    
    (void)jenv;
    (void)jcls;
    result = (uid_t)geteuid();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_getuid(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    uid_t result;
    
    (void)jenv;
    (void)jcls;
    result = (uid_t)getuid();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1genericfs(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1get_1free_1space(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    size_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    try {
        result = (size_t)(arg1)->get_free_space();
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1get_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    jlong jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    std::string *arg2 = 0 ;
    size_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return 0;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        result = (size_t)(arg1)->get_size((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    catch(std::logic_error &_e) {
        (void)_e;
        SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ std::logic_error exception thrown");
        return 0;
        
    }
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1get_1last_1modification_1time(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    jlong jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    std::string *arg2 = 0 ;
    time_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return 0;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        result = (time_t)(arg1)->get_last_modification_time((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1get_1exact_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    jlong jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    std::string *arg2 = 0 ;
    size_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return 0;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        result = (size_t)(arg1)->get_exact_size((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    catch(std::logic_error &_e) {
        (void)_e;
        SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ std::logic_error exception thrown");
        return 0;
        
    }
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1get_1exact_1last_1modification_1time(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    jlong jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    std::string *arg2 = 0 ;
    time_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return 0;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        result = (time_t)(arg1)->get_exact_last_modification_time((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1truncate_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
    jint jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    std::string *arg2 = 0 ;
    size_t arg3 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return 0;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    arg3 = (size_t)jarg3; 
    try {
        result = (int)(arg1)->truncate_file((std::string const &)*arg2,arg3);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_genericfs_1new_1acl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    fs::genericfs *arg1 = (fs::genericfs *) 0 ;
    fs_acl *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::genericfs **)&jarg1; 
    try {
        result = (fs_acl *)((fs::genericfs const *)arg1)->new_acl();
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    *(fs_acl **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1posixfs(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    jlong jresult = 0 ;
    std::string *arg1 = 0 ;
    fs::posixfs *result;
    
    (void)jenv;
    (void)jcls;
    if(!jarg1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return 0;
    }
    const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
    if (!arg1_pstr) return 0;
    std::string arg1_str(arg1_pstr);
    arg1 = &arg1_str;
    jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
    try {
        result = (fs::posixfs *)new fs::posixfs((std::string const &)*arg1);
    }
    catch(fs::acl_not_supported &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/AclNotSupported");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    *(fs::posixfs **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_posixfs_1new_1acl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    fs::posixfs *arg1 = (fs::posixfs *) 0 ;
    fs_acl *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::posixfs **)&jarg1; 
    try {
        result = (fs_acl *)((fs::posixfs const *)arg1)->new_acl();
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return 0;
        }
    }
    
    *(fs_acl **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1posixfs(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs::posixfs *arg1 = (fs::posixfs *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs::posixfs **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1access(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jintArray jarg4) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    uid_t arg3 ;
    std::vector<gid_t > arg4 ;
    bool result;
    jint *jarr4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    arg3 = (uid_t)jarg3; 
    {
        if (!SWIG_JavaVectorInInt(jenv, &jarr4, &arg4, jarg4)) 
        return 0; 
    }
    result = (bool)((fs_acl const *)arg1)->access(arg2,arg3,arg4);
    
    jresult = (jboolean)result; 
    {
        SWIG_JavaVectorArgoutInt(jenv, jarr4, arg4, jarg4); 
    }
    /*delete arg4;*/ 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs_acl *arg1 = (fs_acl *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    (arg1)->clear();
    
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1load_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jboolean jarg3) {
    fs_acl *arg1 = (fs_acl *) 0 ;
    std::string *arg2 = 0 ;
    bool arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return ;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return ;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    arg3 = jarg3 ? true : false; 
    try {
        (arg1)->load((std::string const &)*arg2,arg3);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(std::exception &_e) {
        {
            jclass excep = jenv->FindClass("java/lang/RuntimeException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1load_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    fs_acl *arg1 = (fs_acl *) 0 ;
    std::string *arg2 = 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return ;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return ;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        (arg1)->load((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(std::exception &_e) {
        {
            jclass excep = jenv->FindClass("java/lang/RuntimeException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1enforce(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    fs_acl *arg1 = (fs_acl *) 0 ;
    std::string *arg2 = 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return ;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return ;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        ((fs_acl const *)arg1)->enforce((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(std::exception &_e) {
        {
            jclass excep = jenv->FindClass("java/lang/RuntimeException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1fs_1acl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    fs_acl *arg1 = (fs_acl *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1group_1owner_1gid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (gid_t)((fs_acl const *)arg1)->get_group_owner_gid();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1group_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_group_owner_perm();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1mask(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_mask();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1other_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_other_perm();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_owner_perm();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1owner_1uid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (uid_t)((fs_acl const *)arg1)->get_owner_uid();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1has_1group_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    result = (bool)((fs_acl const *)arg1)->has_group_perm(arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1has_1user_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    result = (bool)((fs_acl const *)arg1)->has_user_perm(arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1has_1explicit_1mask(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (bool)((fs_acl const *)arg1)->has_explicit_mask();
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1is_1group_1perm_1masked(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    result = (bool)((fs_acl const *)arg1)->is_group_perm_masked(arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1is_1group_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    result = (bool)((fs_acl const *)arg1)->is_group_owner(arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1is_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    result = (bool)((fs_acl const *)arg1)->is_owner(arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1is_1permission_1subset(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl::permission_t arg1 ;
    fs_acl::permission_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (fs_acl::permission_t)jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (bool)fs_acl::is_permission_subset(arg1,arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1is_1user_1perm_1masked(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    result = (bool)((fs_acl const *)arg1)->is_user_perm_masked(arg2);
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1group_1effective_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_group_effective_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1group_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_group_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1user_1effective_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_user_effective_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1user_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    result = (fs_acl::permission_t)((fs_acl const *)arg1)->get_user_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1group_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->grant_group_owner_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1group_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->grant_group_perm(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1group_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->grant_group_perm_not_owner(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1other_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->grant_other_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->grant_owner_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1user_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->grant_user_perm(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1grant_1user_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->grant_user_perm_not_owner(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jboolean JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1has_1extended_1acl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jboolean jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    bool result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (bool)((fs_acl const *)arg1)->has_extended_acl();
    
    jresult = (jboolean)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1remove_1group_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->remove_group_perm_not_owner(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1remove_1user_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->remove_user_perm_not_owner(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1group_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->revoke_group_owner_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1group_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->revoke_group_perm(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1group_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->revoke_group_perm_not_owner(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1other_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->revoke_other_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->revoke_owner_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1user_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->revoke_user_perm(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1revoke_1user_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->revoke_user_perm_not_owner(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1group_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->set_group_owner_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1group_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->set_group_perm(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1group_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    gid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (gid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->set_group_perm_not_owner(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1mask(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->set_mask(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1other_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->set_other_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1owner_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    fs_acl::permission_t arg2 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (fs_acl::permission_t)jarg2; 
    result = (fs_acl::permission_t)(arg1)->set_owner_perm(arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1user_1perm(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->set_user_perm(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1set_1user_1perm_1not_1owner(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    jint jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    uid_t arg2 ;
    fs_acl::permission_t arg3 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    arg2 = (uid_t)jarg2; 
    arg3 = (fs_acl::permission_t)jarg3; 
    result = (fs_acl::permission_t)(arg1)->set_user_perm_not_owner(arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1size(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    size_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (size_t)((fs_acl const *)arg1)->size();
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jintArray JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1uid_1list(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jintArray jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    std::vector<uid_t > result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (arg1)->get_uid_list();
    
    {
        jresult = SWIG_JavaVectorOutInt(jenv, result, (&result)->size());
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1uid_1list_1size(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    size_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (size_t)(arg1)->get_uid_list_size();
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jintArray JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_fs_1acl_1get_1gid_1list(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jintArray jresult = 0 ;
    fs_acl *arg1 = (fs_acl *) 0 ;
    std::vector<gid_t > result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(fs_acl **)&jarg1; 
    result = (arg1)->get_gid_list();
    
    {
        jresult = SWIG_JavaVectorOutInt(jenv, result, (&result)->size());
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_new_1posixfs_1acl(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    posixfs_acl *result;
    
    (void)jenv;
    (void)jcls;
    result = (posixfs_acl *)new posixfs_acl();
    
    *(posixfs_acl **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_posixfs_1acl_1load_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jboolean jarg3) {
    posixfs_acl *arg1 = (posixfs_acl *) 0 ;
    std::string *arg2 = 0 ;
    bool arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(posixfs_acl **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return ;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return ;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    arg3 = jarg3 ? true : false; 
    try {
        (arg1)->load((std::string const &)*arg2,arg3);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::invalid_path &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/InvalidPathException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::permission_denied &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/InvalidPathException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::acl_not_supported &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/AclNotSupported");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(std::exception &_e) {
        {
            jclass excep = jenv->FindClass("java/lang/RuntimeException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_posixfs_1acl_1load_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    posixfs_acl *arg1 = (posixfs_acl *) 0 ;
    std::string *arg2 = 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(posixfs_acl **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return ;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return ;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        (arg1)->load((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::invalid_path &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/InvalidPathException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::permission_denied &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/InvalidPathException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::acl_not_supported &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/AclNotSupported");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(std::exception &_e) {
        {
            jclass excep = jenv->FindClass("java/lang/RuntimeException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_posixfs_1acl_1enforce(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    posixfs_acl *arg1 = (posixfs_acl *) 0 ;
    std::string *arg2 = 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(posixfs_acl **)&jarg1; 
    if(!jarg2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
        return ;
    }
    const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
    if (!arg2_pstr) return ;
    std::string arg2_str(arg2_pstr);
    arg2 = &arg2_str;
    jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
    try {
        ((posixfs_acl const *)arg1)->enforce((std::string const &)*arg2);
    }
    catch(fs::error &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/FilesystemError");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::invalid_path &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/InvalidPathException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::permission_denied &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/InvalidPathException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(fs::acl_not_supported &_e) {
        {
            jclass excep = jenv->FindClass("it/grid/storm/filesystem/AclNotSupported");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    catch(std::exception &_e) {
        {
            jclass excep = jenv->FindClass("java/lang/RuntimeException");
            if (excep)
            jenv->ThrowNew(excep, (&_e)->what());
            return ;
        }
    }
    
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_posixfs_1acl_1to_1permission_1t(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    unsigned short arg1 ;
    fs_acl::permission_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (unsigned short)jarg1; 
    result = (fs_acl::permission_t)posixfs_acl::to_permission_t(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_posixfs_1acl_1from_1permission_1t(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    fs_acl::permission_t arg1 ;
    acl_perm_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (fs_acl::permission_t)jarg1; 
    result = (acl_perm_t)posixfs_acl::from_permission_t(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_delete_1posixfs_1acl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    posixfs_acl *arg1 = (posixfs_acl *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(posixfs_acl **)&jarg1; 
    delete arg1;
    
}


JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGsystem_1errorUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs::error **)&baseptr = *(fs::system_error **)&jarg1;
    return baseptr;
}

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGacl_1not_1supportedUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs::error **)&baseptr = *(fs::acl_not_supported **)&jarg1;
    return baseptr;
}

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGinvalid_1pathUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs::error **)&baseptr = *(fs::invalid_path **)&jarg1;
    return baseptr;
}

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGpermission_1deniedUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs::error **)&baseptr = *(fs::permission_denied **)&jarg1;
    return baseptr;
}

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGwrong_1filesystem_1typeUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs::error **)&baseptr = *(fs::wrong_filesystem_type **)&jarg1;
    return baseptr;
}

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGposixfsUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs::genericfs **)&baseptr = *(fs::posixfs **)&jarg1;
    return baseptr;
}

JNIEXPORT jlong JNICALL Java_it_grid_storm_filesystem_swig_posixapi_1interfaceJNI_SWIGposixfs_1aclUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(fs_acl **)&baseptr = *(posixfs_acl **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

