/*
 *
 *  Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2006-2010.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class posixapi_interface {
  public static int chmod(String path, int mode) {
    return posixapi_interfaceJNI.chmod(path, mode);
  }

  public static int chown(String path, int owner, int group) {
    return posixapi_interfaceJNI.chown(path, owner, group);
  }

  public static int creat(String pathname, int mode) {
    return posixapi_interfaceJNI.creat(pathname, mode);
  }

  public static int mkdir(String pathname, int mode) {
    return posixapi_interfaceJNI.mkdir(pathname, mode);
  }

  public static int setuid(int uid) {
    return posixapi_interfaceJNI.setuid(uid);
  }

  public static int unlink(String pathname) {
    return posixapi_interfaceJNI.unlink(pathname);
  }

  public static int umask(int mask) {
    return posixapi_interfaceJNI.umask(mask);
  }

  public static int geteuid() {
    return posixapi_interfaceJNI.geteuid();
  }

  public static int getuid() {
    return posixapi_interfaceJNI.getuid();
  }

}
