/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class posixfs_acl extends fs_acl {
  private long swigCPtr;

  protected posixfs_acl(long cPtr, boolean cMemoryOwn) {
    super(posixapi_interfaceJNI.SWIGposixfs_aclUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(posixfs_acl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      posixapi_interfaceJNI.delete_posixfs_acl(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public posixfs_acl() {
    this(posixapi_interfaceJNI.new_posixfs_acl(), true);
  }

  public void load(String path, boolean delete_also) throws it.grid.storm.filesystem.FilesystemError, it.grid.storm.filesystem.InvalidPathException, it.grid.storm.filesystem.InvalidPermissionOnFileException, it.grid.storm.filesystem.AclNotSupported, java.lang.RuntimeException {
    posixapi_interfaceJNI.posixfs_acl_load__SWIG_0(swigCPtr, path, delete_also);
  }

  public void load(String path) throws it.grid.storm.filesystem.FilesystemError, it.grid.storm.filesystem.InvalidPathException, it.grid.storm.filesystem.InvalidPermissionOnFileException, it.grid.storm.filesystem.AclNotSupported, java.lang.RuntimeException {
    posixapi_interfaceJNI.posixfs_acl_load__SWIG_1(swigCPtr, path);
  }

  public void enforce(String path) throws it.grid.storm.filesystem.FilesystemError, it.grid.storm.filesystem.InvalidPathException, it.grid.storm.filesystem.InvalidPermissionOnFileException, it.grid.storm.filesystem.AclNotSupported, java.lang.RuntimeException {
    posixapi_interfaceJNI.posixfs_acl_enforce(swigCPtr, path);
  }

  public static int to_permission_t(int perm) {
    return posixapi_interfaceJNI.posixfs_acl_to_permission_t(perm);
  }

  public static int from_permission_t(int perm) {
    return posixapi_interfaceJNI.posixfs_acl_from_permission_t(perm);
  }

}
