/*
 *
 *  Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2006-2010.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class system_error extends error {
  private long swigCPtr;

  protected system_error(long cPtr, boolean cMemoryOwn) {
    super(posixapi_interfaceJNI.SWIGsystem_errorUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(system_error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected system_error() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      posixapi_interfaceJNI.delete_system_error(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public system_error(String msg, int errnum) {
    this(posixapi_interfaceJNI.new_system_error__SWIG_0(msg, errnum), true);
  }

  public system_error(String msg) {
    this(posixapi_interfaceJNI.new_system_error__SWIG_1(msg), true);
  }

  public String getMessage() {
    return posixapi_interfaceJNI.system_error_getMessage(swigCPtr);
  }

  public String error_message(int errnum) {
    return posixapi_interfaceJNI.system_error_error_message(swigCPtr, errnum);
  }

}
