/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class xfs extends posixfs {
  private long swigCPtr;

  protected xfs(long cPtr, boolean cMemoryOwn) {
    super(xfsapi_interfaceJNI.SWIGxfsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xfs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected xfs() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      xfsapi_interfaceJNI.delete_xfs(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public xfs(String mntpath) {
    this(xfsapi_interfaceJNI.new_xfs(mntpath), true);
  }

  public void prealloc(String filename, long size) {
    xfsapi_interfaceJNI.xfs_prealloc(swigCPtr, filename, size);
  }

  public fs_acl new_acl() {
    long cPtr = xfsapi_interfaceJNI.xfs_new_acl(swigCPtr);
    return (cPtr == 0) ? null : new fs_acl(cPtr, false);
  }

}
