/**
 * Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN).
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org). Version
 * 1.3.24
 * 
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package it.grid.storm.griduser.swig;

public class lcmaps_interface {
}
